version: '3'

services:
  bot-lacantina:
    build: .
    container_name: bot-lacantina
    restart: always  # Auto-restart the container on failures
    env_file:
      - .env
    volumes:
      - .:/app  # Mount the current directory to the container
    command: python LaCantina.py
